name: Deploy CDK Build and Deploy Gatsby Website + Contentfull to S3

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
    - uses: actions/checkout@v2

    - name: Npm install
      run : |
        yarn
        npm install -D

    - name: Build
      run : sudo npm run build
      env:
        SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
        AUTH_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

    - uses: actions/checkout@v2
    - name: Configure AWS credentials for CDK
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1 

    - name: install npm
      run : 'sudo apt update -y && sudo apt install nodejs npm -y'

    - name: Install AWS CDK
      run : |
        sudo npm i -g cdk
        sudo npm i aws-cdk-lib
        sudo npm i @aws-cdk/core
        sudo npm i @aws-cdk/aws-s3
        sudo npm i @aws-cdk/aws-s3-deployment
        sudo npm i @aws-cdk/aws-cloudfront

      working-directory: cdk
    
    - name: CDK Bootstrap
      run : cdk bootstrap
      working-directory: cdk

    - name: CDK Synth
      run : cdk deploy
      working-directory: cdk

    - name: CDK Deploy
      run : cdk deploy
      working-directory: cdk